### ISSUE TITLE
Way to use pressure converter without buildcraft pipe

### ISSUE THREAD

**Issue by serhiicherepanov** [Esteemed-Innovation/Flaxbeards-Steam-Power#136]
Hi and many thanks for excellent mod!

I have server with IndustrialCraft2 and RailCraft + ProjectRed.

I use ProjectRed instead buildcraft on my server and i have no any fluid pipes.

RC (RailCraft) steam converted to FSP steam via Pressure Converter, but i not found way to convert FSP steam back to fluid steam (

As far i understand it happen because block connected to converter must pull fluid steam from converter (Like wood pipe in buildcraft). Rc and IC2 not have any device for this (

Will be good if FSP would be have it.

Thanks!

**Comment by Ghoughpteighbteau** [comment]
If I can make a suggestion, why not whack the converter with a wrench and have it behave it toggle it's behavior to act like the railcraft boilers. Railcraft get's around the no BC issue by having boilers push steam to nearby tanks automatically.

Fluid extractors in BC kinda suck anyway.

If I make a pull request, would you be interested?

**Comment by xbony2** [comment]
SatanicSanta? I'm up for whatever.

**Comment by xbony2** [comment]
(@satanicsanta)

**Comment by satanicsanta** [comment]
I agree with

>I'm up for whatever.

**Comment by Ghoughpteighbteau** [comment]
yay. Though it looks like the wrench is disambiguating what it should do with the block, rather than the block telling the wrench what should happen... I'ma follow that code style. Looks simple enough.

**Comment by Flaxbeard** [comment]
Erm, no, the block tells the wrench for everything but pipes (special case)

**Comment by Ghoughpteighbteau** [comment]
Glad I ran that by you guys.

**Comment by satanicsanta** [comment]
Woah, @Flaxbeard is alive.
