### ISSUE TITLE
Exosuit step assist issue

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#153]
The exosuit is currently "saving" the step assist feature to the player after they take it off. This is a major issue, and needs to be fixed.

**Comment by elifoster** [comment]
I have determined that this issue is probably directly related to #185.

**Comment by CurePindal** [comment]
Was the step assist removed? Seems no longer available in 0.28.x!

**Comment by elifoster** [comment]
No... I was just using it in my dev environment. You have to be wearing the boots.

**Comment by elifoster** [comment]
I'm no longer able to reproduce this issue, oddly.

**Comment by elifoster** [comment]
This was fixed at some point between March 6 and now. Myself and the @Esteemed-Innovation/testing-monkeys have confirmed this.
