### ISSUE TITLE
MineTweaker Support

### ISSUE THREAD

**Issue by UndeadZeratul** [Esteemed-Innovation/Flaxbeards-Steam-Power#179]
I'm aware Modtweaker currently adds support, but @joshiejack has stopped working on it a while ago.  I don't know his policies on giving you the code to integrate it with FSP, but I saw Blood Magic now has the classes from ModTweaker, and they're credited to Josh. [Here's](https://github.com/joshiejack/ModTweaker/tree/master/src/main/java/modtweaker/mods/fsp) the classes you'd need to implement in order to get it working.

**Comment by UndeadZeratul** [comment]
Fair enough, just curious.

**Comment by xbony2** [comment]
Going to close this issue, since JaredIII08 (and some other people who are also noteworthy, but I'm too lazy to list them anyway) has been maintaining ModTweaker.

**Comment by UndeadZeratul** [comment]
Ah, yeah I forgot we left this open.  If they're going to be maintaining it, no reason to keep it open here.
