### ISSUE TITLE
High increase in client upload bandwidth usage

### ISSUE THREAD

**Issue by Nentify** [Esteemed-Innovation/Flaxbeards-Steam-Power#183]
Hello

Something in this mod when installed on the client is causing high increases in client upload bandwidth usage. When testing, removing the mod causes upload bandwidth usage to settle at around 200 B/sec. However, when installing the mod on the client and joining a server, this value increases to between 8000-11000 B/sec.

MPS had a similar issue in 1.5.2 where packets were very large (in the armour) and it was soon fixed if that is of any help.

**Comment by LemADEC** [comment]
Is this issue still valid?

**Comment by Nentify** [comment]
dont know :)

**Comment by elifoster** [comment]
Closing this in favor of #344 because it has more information.
