### ISSUE TITLE
Exo Suit Chestplate keeps Steam without tank

### ISSUE THREAD

**Issue by CurePindal** [Esteemed-Innovation/Flaxbeards-Steam-Power#185]
Hello. Found what seems to be a bug. 
The exo suit body keeps its steam level and functionality when you remove the tank from the piece.

1. Remove a tank with steam from the body part of the suit.
2. The tank is removed but the body part still shows the previous steam level and works as if it still has this steam level. 
3. The body suit even shows the previous capacity and can be charged up with steam without any tank.

Expected: Steam level and capacity gets set to zero when the tank gets removed. 
Looks as if theres an item update missing. The body suit level gets set to zero when you add a new tank.

**Comment by elifoster** [comment]
Hm. I think this might be related to the problem I'm having with the zinc plate from #337...

**Comment by elifoster** [comment]
Okay, we really have 3 options for fixing this:
1. We can set an NBT value "hasTank" when the tank is added/removed, and check that before checking if it `hasPower`.
2. We can check the exosuit's upgrades every time we check its power.
3. We can store the steam in the tank itself, which might cause problems in the block's case.

@Divineaspect @xbony2 thoughts?

**Comment by Divineaspect** [comment]
Slight preference for 2, in so far as I understand this.

**Comment by elifoster** [comment]
Close by @e176a80.
