### ISSUE TITLE
Transfer of ownership

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#221]
@Flaxbeard Please transfer ownership of this repository to the organization, Esteemed-Innovation.

**Comment by elifoster** [comment]
@Flaxbeard In case I need to add some reasoning:

1. We may need to add/remove people as contributors in the future.
2. We may want to do FSP-related projects as well as FSP.
3. We may want to change the description and URL
4. We may want to change some settings such as webhooks and services
5. We may decide to change the name because having someone's name in a mod name is dumb. It's not "Azanor's Thaumcraft" or "CovertJaguar's Railcraft".

**Comment by elifoster** [comment]
@Flaxbeard I'll add you and all the other contributors to the organization as soon as the repo gets transferred over. Don't tell me to fork it, because Git doesn't allow searching forked repos or transferring issues from the original to a fork. There are many other features that normal repositories have but forks don't.

**Comment by xbony2** [comment]
Forks are buggy and annoying :/

I'm against changing the name, just "Steam Power" or "SteamCraft" sounds dumb.

**Comment by elifoster** [comment]
I was thinking "Esteemed Innovation".

**Comment by xbony2** [comment]
That's better. Still though, changing the mod's name is likely to cause much confusion, it's already well-known as FSP.

**Comment by elifoster** [comment]
I dunno. I feel weird working on a project that is labeled as "One other person's project". The name's also changed like twice in the past already. The name would be changed only once we move out of beta and into release.

**Comment by Flaxbeard** [comment]
Done.

**Comment by elifoster** [comment]
Okay, so it turns out you, @Flaxbeard, have to be an owner of the org to transfer ownership. Pls try it again bb <3
