### ISSUE TITLE
Unable to remove recipes to the crucible.

### ISSUE THREAD

**Issue by jaredlll08** [Esteemed-Innovation/Flaxbeards-Steam-Power#223]
Hey there, I'm the new author of ModTweaker. and it is not allowing me to remove recipes from the crucible :/ I can add recipes fine, but if you try to remove, it just doesn't work, and it doesn't give an error...

**Comment by jaredlll08** [comment]
A link to the code can be found here:
https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker2/mods/fsp/handlers/Crucible.java

Thanks

**Comment by Yulife** [comment]
https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker2/mods/fsp/handlers/Crucible.java#L69
;D

**Comment by elifoster** [comment]
Closing in favor of #327
