### ISSUE TITLE
NEI Support

### ISSUE THREAD

**Issue by karmarcharger** [Esteemed-Innovation/Flaxbeards-Steam-Power#243]
It would be rather useful to have NEI support for dunking and crucible ore mixing ;)

**Comment by xbony2** [comment]
I'd volunteer to work on this if I had experience with NEI :P this is the sort of thing that needs to be done.

**Comment by elifoster** [comment]
I agree. It's pretty standard for mods to have this.

**Comment by elifoster** [comment]
Closing in favor of #328
