### ISSUE TITLE
Add support for other fluid containers than Items.water_bucket

### ISSUE THREAD

**Issue by vidaj** [Esteemed-Innovation/Flaxbeards-Steam-Power#245]
Hi

The code for inputting water into a boiler is a bit to vanilla specific to allow good inter-mod cooperation. Specifically BlockBoiler#onBlockActivated only checks for a vanilla water bucket. If you instead replace the water check with something like this:
```java
public static boolean handleFillBoiler(World par1World, int par2, int par3, int par4, EntityPlayer player) {
		ItemStack heldItem = player.getHeldItem();
		FluidStack heldFluid = FluidContainerRegistry.getFluidForFilledItem(heldItem);
		
		if (heldItem == null || heldFluid == null || heldFluid.getFluid() != FluidRegistry.WATER) {
			return false;
		}
		
		ItemStack emptyBucket = heldItem.getItem().getContainerItem(heldItem);
		TileEntityBoiler tileentityboiler = (TileEntityBoiler) par1World.getTileEntity(par2, par3, par4);
		
		int amountFilled = tileentityboiler.fill(ForgeDirection.UP, heldFluid, true);
		if (!player.capabilities.isCreativeMode && amountFilled != 0) {
			player.inventory.setInventorySlotContents(player.inventory.currentItem, emptyBucket);
		}
		
		return true;
	}
```

This will allow other mods to use their buckets or fluid containers without you knowing about their containers. I ASM-d in the above mentioned method and tried to use a TerraFirmaCraft wooden bucket, and it worked like a charm.

I did a search for "Items.water_bucket" in the repo, and found 5 files that referenced it, so I guess all five places need some rewriting.

**Comment by xbony2** [comment]
You should send a pull request :P

**Comment by elifoster** [comment]
I agree with @xbony2

**Comment by vidaj** [comment]
I will create a pull request soon :)

**Comment by elifoster** [comment]
@vidaj Do you happen to still have your clone of FSP? If so, you should totally submit a PR :wink:

@xbony2 if @vidaj does not reply for a bit, do you think you could deal with this since it is crossmod?

**Comment by vidaj** [comment]
Sorry, things happened, so I never got around to this. I'm cloning and fixing code as we speak. PR will come through tonight or tomorrow.

**Comment by elifoster** [comment]
Sweet!
