### ISSUE TITLE
Steam Tool upgrades

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#251]
Allowing the Steam Tools to get an upgrade or two would make them a lot more useful. Names subject to change.

* [x] Re implement second durability bar, remove sound crap
* [ ] AoE mining: Fast (or particles???): Only a single block's particles are shown. Fancy: All block particles are shown
* [x] Tank
  * [x] Link Exosuit tank with Steam Tools
  * [x] Steamcells
    * [x] code
    * [x] recipes
    * [x] lang
    * [x] textures
      * Note that this is actually 3 items: Steam cell filler, empty steam cell, and full steam cell
* [ ] Drill
  * [x] Texture loading
  * [x] Engineering Table stuff
    * [x] Background
    * [x] Slots
  * [ ] Drill head upgrades
    * [x] Dynamic metal storage block upgrades to modify tool harvest level
      * [x] Code
      * [x] Recipe
      * [x] Lang
      * [x] Texture: exactly the same as drillHeadBase0
      * TODO: Figure out how to deal with the book
    * [x] Multiplicative Resonator
      * [x] Code
      * [x] Recipe
      * [x] Lang
      * [x] Texture
    * [x] Big Drill
      * 3x3 mining
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Texture
    * [x] Battle Drill
      * Less effective as a mining tool, way way more damage. Not quite as much as the Chainsaw, because the drill adds the drill dash. Sweet sounds and animations. Drill dash key allows you to charge a few blocks forward and deal a shit ton of damage to whoever is front of you. Costs a bunch of steam
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Texture
    * [x] Precise Cutting Head
      * Silk touch
        * [x] Code
        * [x] Recipe
        * [x] Book Entry
        * [x] Texture
    * [x] Stone Grinder
      * Grinds up stone so that it doesn't drop, but has a chance of dropping ore nuggets.
        * [x] Code
        * [x] Recipe
        * [x] Book Entry
        * [x] Texture
    * [x] Thermal Drill
      * Note: @Flaxbeard coded this for one of his unreleased mods, and he either gave grace to use that code, or will submit a PR.
      * Melts stone into a small amount of lava, in exchange for mining it super fast. This lava goes away pretty quick.
        * [x] Code
        * [x] Recipe
        * [x] Book Entry
        * [x] Texture
    * [x] Calamity Injector
      * Mines really really quickly but does not drop anything. Replaces the block with an explosive charge (high pressure steam into the cracks of the rock) that will explode in X amount of time after placing. Increases steam cost due to the extra steam it has to emit. 
      * Similar situation to Thermal Drill in relation to @Flaxbeard and his unreleased mods
        * [x] Code
        * [x] Recipe
        * [x] Book Entry
        * [x] Texture
  * [x] Core
    * [x] Internal Processing Unit
      * Acts as the rock smasher, but is slower. Extra steam cost.
        * [x] Code
        * [x] Recipe
        * [x] Book Entry
        * [x] Texture
    * See bottom of this issue
* [ ] Saw
  * [x] Texture loading
  * [x] Engineering Table stuff
    * [x] Background
    * [x] Slots
  * [ ] Saw head upgrades
    * [ ] Forest Fire
      * Burning a large area, roughly 15x15, of trees
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [ ] Texture
    * [x] Timber Chain
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Texture
    * Planker saw mill thing
    * [x] Leaf Blower
      * Instantly clear leaves in 3x3, but it can no longer cut wood efficiently
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Texture
    * [x] Chainsaw
      * Less effective as a felling tool, but way way more effective as a weapon. More damage than BattleDrill default, but roughly the same as BattleDrill dash. Sweet sounds and animations.
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Texture
  * [x] Core upgrades
    * See bottom of this issue
* [ ] Shovel
  * [x] Texture loading
  * [x] Engineering Table stuff
    * [x] Background
    * [x] Slots
  * [ ] Shovel head upgrades
    * [x] Backhoe
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Texture
    * [ ] Cultivator
      * Prevents tool from digging, but allows for 3x3 tilling
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [ ] Texture
    * [x] Rotary Blades
      * Digging 3x3 blocks
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Texture
  * [x] Core upgrades
    * See bottom of this issue
    * [x] Sifter
      * Small chance of getting seeds and bones from mining dirt, but does not yield actual dirt blocks.
      * Increases chance of getting flint (not 100%), but does not yield actual gravel blocks.
      * Tiny chance of getting gold nuggets from sand, but does not yield actual sand blocks.
        * [x] Code
        * [x] Recipe
        * [x] Book Entry
        * [x] Texture
* [x] Upgrades applicable to multiple devices
  * Note that this is possible, as shown by some Flintlock Weapon upgrades
  * [x] Overclocker
    * [x] All tools: Core upgrade that increases mining speed as well as steam cost
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Drill Texture
      * [x] Saw Texture
      * [x] Shovel Texture
  * [x] Exothermic Projector
    * [x] All tools: Core upgrade that automatically drop smelted version of block instead of the block
      * [x] Code
      * [x] Recipe
      * [x] Book Entry
      * [x] Drill Texture
      * [x] Saw Texture
      * [x] Shovel Texture
  * [x] The Void
    * [x] Code
    * [x] Recipe
    * [x] Book Entry
    * [x] Drill Texture
    * [x] Saw Texture
    * [x] Shovel Texture

# Community ideas
These ideas were provided by the communities at the [FTB Forum](http://forum.feed-the-beast.com/threads/flaxbeards-steam-power-suggestion-thread.51928/page-7#post-1541584) and the [FTB Subreddit](https://www.reddit.com/r/feedthebeast/comments/3zltzg/what_upgrades_for_steam_tools_would_you_like_to/). The bulletpoints are *exactly* as they were posted.
### General
* Heavy Flywheel: Tools stay spinning for longer, but takes 10-20% extra steam to rev up.
* High Pressure Drive: Revs up 50% faster but slows down faster. 
* Emergency Flash Exaust: On command you consume 25% of your steam to create a heavy mist cloud that slows mobs and dampens creeper explosions. 
* Obviously usage upgrades, like Diamond-tipped for efficiency, Lustre-coated for Fortune drops, that kind of thing.
* Dull Tips: Turns Ores into Smashed Ore, Gravel into multiple pieces of Flint and Logs into Planks.
* Zinc Boiler/Zinc Bucket (works for the Exosuit too): The Zinc Boiler is applied to a tool, and will hold Water. The Zinc Bucket is used to get the water in there: Any water picked up by the Bucket will be evenly distributed to all Zinc Boilers on tools in your inventory, possible losing a few millibuckets to even it all out. When the tool is out of Steam, the Boilers will then automatically take fuel from your inventory to produce more Steam in your Boilers.

### Drill
* ~~Tiered and AoE upgrades. The drill is awesome, but ends up outclassed by the harder picks (such as diamond) and/or AoE options (TiCon hammer, etc).~~ *Big Drill and Diamond Head*
* Hammerdrill upgrade - chance to drop bonus chunks of smashed ore.
* ~~Jackhammer upgrade - much faster operation, but drops nothing.~~ *Thermal Drill and Quick Mining Head*
* Could use some mining level and speed upgrades, if this page[1] is to be believed about it being iron pickaxe level.
* Fortune & ~~Silk Touch~~ would be nice on the drill
* ~~Pulverizer Bore Head: Mining speed of stone is greatly increased, and all stone mined is destroyed, but with a small (~5%?) chance of dropping random metal nuggets in their place.~~ *Stone Grinder*

### Saw
* "Forest Fire" You know those forests! They crowd that cool spot where you would like to setup base and it takes a good hour to clear it. Its tedious and boring. Not with the Forest Fire upgrade! When activated and used to cut a tree it ignites nearby trees and burns them down within seconds (accelerated fire) clearing 15x15 area of trees.
* "Planker" When activated whenever the saw is used it will break the log down into planks giving a 3.0x more planks than normally able to. Costs 10x more steam.
* ~~Once high enough in the tech tree, do you really need a saw when you could have an automated tree farm? Why not have some upgrades that slow the wood chopping but add extra damage when used to attack (migrate from a tool to a weapon).~~ *Chainsaw*
* A treecapitator style upgrade - everything above it gets knocked down and the blocks/leaves fall down to the ground.
* Can't remember if they can be used as shears, but that could be an option for an upgrade.
* ~~Make an object (ala the steam hammer) where you can mount your saw and use it as a saw mill.~~ *Duplicate idea of "Planker"*
* Just stick jam an axe of the stream in there and steal the functionality. Thaumium plate giving Repair-like functionality? 
* ~~Tree Felling (like Tinkers Lumber Axe) on the chainsaw. Damage on I think it's the chainsaw might be worthwhile.~~ *Duplicate of "A treecapitator style upgrade"*
* Precision Blade: When used on leaves, doubles the chance to find Saplings, and drops 0-1 sticks.
* ~~a sawmill upgrade for the axe that makes all mined logs drop 6 planks.~~ *Duplicate of "Planker"*

### Shovel
* ~~Autosifter upgrade - vastly increased steam usage, has a chance to drop nuggets and destroy the dirt/sand/gravel. Drops something else on soul sand (not sure what though).~~ *Sifter, though Soul Sand was not even considered*
* Flicker upgrade - Hit a mob with it and knock it back like you'd fling a shovel full of stuff away. Faster wind up on the shovel means more distance. Does token damage, but the fall will hurt... Hit rock or some hard block, and it sends you flying instead.
* How about, in the vein of elementium shovels, "will dig all blocks of the same material affected by gravity above and below the mined block"?
* ~~Tiller (Activate with shift-rightclick): While active, right-click tills earth at a small cost of Steam~~ *Cultivator*
* One slightly odd idea I have is to make a brick-maker upgrade for the shovel. Mining clay with it would double the drops to make up for clay's relative rarity, but would also smelt them into bricks so that it cannot be abused for clay duplication. As bricks looks nice with FSP's steampunk factory aesthetic, it would be quite useful for obtaining materials.
* ~~There could also be a macerator upgrade for the shovel that guarantees that gravel drop flint and maybe makes it drop 2 or 3 pieces~~ *Sifter*

### General
* custom material drill heads, such as titanium or steel, or even something from Metallurgy. This should be fairly simple to implement as a dynamically generated list of drill heads based off of what items are registered as ingots in the ore dictionary, which I guess means there should also be plates for each ingot.
* ~~"Overclock" Maybe there could be something like redstone arsenal like the "Empowered" mode so it decreases the time it takes for a block to break (Like 1/7th of the time) however it uses a massive amount of steam (Say 10x) then it is unable to mine anything besides stone as it ruins the ores or it makes any block it mines unusable.~~ *Overclocker and a bunch of other speed upgrades*
* "The Void" The Void upgrade costs something like a few ender pearls to activate the Void ability on the drill/shovel. The void ability voids works like an enderpouch and transport all of the goodies you mine with the drill or shovel to the chest its bound to.
* Any tool can have an emergency attack (shift attack?) that does a knockback V effect (and steam damage) for a large amount of steam. It could be an AOE (cone-shaped) instead and use all remaining steam (damage and knockback depends on remaining steam level).
* As an inverse to the ideas posted already, some sort of efficiency module that lets you use less steam but increases the time it takes to mine a block would be interesting.
* ~~On other notes, being able to siphon steam from the exosuit for in field refill would be nice. I find I run out real fast, and the steam tools are kinda meh against tinker's tools anyway.~~ *"Link Exosuit tank with Steam Tools"*
* It might be nice to leverage the random plates we have from different mods for armor somehow, although I don't know how that would work.
* Not an upgrade to tools, but I'd really like to see more ways of generating steam other than just burning furnace fuels 
  * Maybe Igneous Extruder generating steam since that's lava hitting water? A problem is that it's free steam...
  * A really early low output steam turbine for RF production. It could work with a valve system where you could open the valve to run the turbine and close the valve to preserve fuel.
* "On board" micro boilers. If you install this on your tool, you can right click water to put a bucket of water in the tool, and open up a UI of the tool to put one burnable item to generate some steam directly.
Of course it would be lower efficiency, and would take longer, but, it could be used in emergencies.

**Comment by CasinoR** [comment]
3x3 mining is extremely op (tinker's hammer forexample). I suggest a belanced 2x1 or 3x1. vertical mining tools are plugin friemdly...

**Comment by elifoster** [comment]
Why is 3x3 op?

**Comment by CasinoR** [comment]
if you dig with 3*3 you show 12 blocks or more with a single use. Normal pickaxe is just 3.

**Comment by elifoster** [comment]
I don't see what the problem with that is. I could just have different mods, 3x1, 1x3, 1x1, and 3x3? Each would use correct amounts of steam according to the base number (1x1).

**Comment by Flaxbeard** [comment]
I would suggest not making several mods that have similar effects, it seems to me to be too... nuanced? If 3x3 means 3 up 3 across but only 1 deep like the thaumcraft tools, then I think that's fine.

**Comment by elifoster** [comment]
All of that was what I had planned, Flax :+1:

**Comment by justicesays** [comment]
for the hammer head, only mining away "stone" (ie. pick accelerated when breaking) blocks in the 3x3 would be a balancing factor, in case that's not already the plan...

**Comment by elifoster** [comment]
Updated upgrade list based on a discussion with @Flaxbeard this evening.

**Comment by Flaxbeard** [comment]
The sifter is doubled up on there under the drill, grinder is probably the better of the two names.

I'll get to work on texturing ASAP, then porting over the code.

**Comment by elifoster** [comment]
@Flaxbeard should the battle drill require the player to be jumping and sprinting, or should a keybind cause the player to leap? Right now in my dev environment I have it set up to work as the former, and it's a bit annoying to use.

**Comment by elifoster** [comment]
Just so everyone who may have cloned the branch knows, the branch has been rebased to master.

**Comment by Divineaspect** [comment]
A few of these ideas talk about the automation upgrade item, I'm ignoring them because I know it's planned, but things like the sawmill, etc. I'm also ignoring things I know which are already in the divine-exo-upgrades or the tool upgrade in some form.

A Lot of these items list things like 10x cost, ignore that, make it about 1.5 increase in cost. Duration of tools already sucks, even with the planned exosuit boilers.


Drill
Scaling Drill Heads: Could we make a slot on the drill to basically take a block of any material, and use that as the drill's point? and mine at  the mining level that a pick of that material would use?
Fortune and Silk Touch: This is unbelievably important. 

Saw
Forest Fire: is much in demand since factorization removed it's area clearing fire. 
Planker: also consider random sticks and sawdusts (if annother mod adds sawdust) combine with the leaf effect to increase drops.
Treecapitation/Felling: Would be enough to make be do FSP before TinCon.

Shovel
Flicker: Massive knockback should really be a inherent quality of the tool, adding in an upgrade to make it silly strong would be good though.
Backhoe: To affect all blocks of the same type in a pillar with it, as per elementium shovels, would certainly speed up construction projects.

General
void/ Enderchest connection: clever and ties in with vanilla.
Other Steam Generation Methods: I concur with this, but suggest that it be handled through the geysers discussed for worldgen features.
Microboilers: Would presently be a bit unbalanced and magic block/item like. I have a more indepth solution for this problem as part of worldgen features.

**Comment by SkeletonPunk** [comment]
@elifoster Are the textures for the tool upgrades going to be visible on the tools themselves?

**Comment by elifoster** [comment]
@SkeletonPunk Yeah, you can kinda see how it works in the following picture:

![this picture](http://puu.sh/mjOOX/9a85a4f7b1.png)

Notice how the drill head is much larger; that's the Big Drill upgrade. All the existing upgrades are at the [resources repo](https://github.com/esteemed-innovation/flaxbeards-steam-power-resources).

**Comment by Flaxbeard** [comment]
I don't think the battle drill should require you to be jumping at all, just charging.

**Comment by SkeletonPunk** [comment]
@elifoster seems like some of the textures that aren't check off are already in the mod resources, should I still do them?

**Comment by elifoster** [comment]
@SkeletonPunk no just do the ones that aren't in the resources.

@Flaxbeard that is the plan, just gotta get around to rewriting it

**Comment by elifoster** [comment]
@Flaxbeard You should totally put the code for the Thermal Drill and Charge Placer somewhere that I can look at.
