### ISSUE TITLE
Block placers can't place into spaces occupied by replacable things, such as water

### ISSUE THREAD

**Issue by justicesays** [Esteemed-Innovation/Flaxbeards-Steam-Power#255]
Block placers won't place blocks into water spaces, not even running water, which placing a block by hand would normally replace.

**Comment by elifoster** [comment]
As stated in that commit, this is now fixed. You'll just need to wait for the automation update, which will happen as soon as features-automation is able to be merged with master.

**Comment by elifoster** [comment]
I don't know why I reopened this. This issue was resolved.
