### ISSUE TITLE
Redstone valve control could do with being consistent.

### ISSUE THREAD

**Issue by justicesays** [Esteemed-Innovation/Flaxbeards-Steam-Power#263]
When enabling the redstone valve control option, the valve state is reversed by a redstone signal, rather than (say) an active signal closing a valve and no signal opening it.
This reversing logic appears to cause some issues, as I have had valves "jam open" in system setups, such as a comparator set up to a furnace to turn a block breaker off when the furnace is getting full.
It would be easier and more consistent if a redstone signal always closed a valve, and a loss of signal caused it to reopen. Some kind of update check on chunk load to make sure it checks it's current signal state would be needed as well I suspect.

**Comment by elifoster** [comment]
@Strikingwolf Do you think you could take a look at this?

**Comment by Strikingwolf** [comment]
Yeah I can, would have to be this weekend though

**Comment by elifoster** [comment]
@Strikingwolf Do you still want to deal with this one?
