### ISSUE TITLE
Support Iguana Tinker Tweaks harvest levels

### ISSUE THREAD

**Issue by lokster666** [Esteemed-Innovation/Flaxbeards-Steam-Power#266]
15.04 10:21:41 [Server] Server thread/ERROR [IguanaTweaksTConstruct]: Could not set harvestlevel of item.steamcraft:shovelGildedGold. Contact the Mod Author to properly support Item.setHarvestLevel().
15.04 10:21:41 [Server] Server thread/ERROR [IguanaTweaksTConstruct]: Could not set harvestlevel of item.steamcraft:axeGildedGold. Contact the Mod Author to properly support Item.setHarvestLevel().
15.04 10:21:41 [Server] Server thread/ERROR [IguanaTweaksTConstruct]: Could not set harvestlevel of item.steamcraft:pickGildedGold. Contact the Mod Author to properly support Item.setHarvestLevel().
15.04 10:21:41 [Server] Server thread/ERROR [IguanaTweaksTConstruct]: Could not set harvestlevel of item.steamcraft:shovelBrass. Contact the Mod Author to properly support Item.setHarvestLevel().
15.04 10:21:41 [Server] Server thread/ERROR [IguanaTweaksTConstruct]: Could not set harvestlevel of item.steamcraft:axeBrass. Contact the Mod Author to properly support Item.setHarvestLevel().
15.04 10:21:41 [Server] Server thread/ERROR [IguanaTweaksTConstruct]: Could not set harvestlevel of item.steamcraft:pickBrass. Contact the Mod Author to properly support Item.setHarvestLevel().

**Comment by xbony2** [comment]
Explains itself pretty well :3
