### ISSUE TITLE
Mod System Refactor

### ISSUE THREAD

**Issue by xbony2** [Esteemed-Innovation/Flaxbeards-Steam-Power#271]
I currently do not like the way mod integration is set up. I'd like to refactor it to be more like [this](https://github.com/xbony2/IndustrialEx).

**Comment by elifoster** [comment]
I like how youve done it there,  and i agree fsp should be refactored to do it like that. Make sure to use a branch.

**Comment by xbony2** [comment]
Alright. Don't touch anything crossmod related.

**Comment by xbony2** [comment]
Or Gradle, as well.

**Comment by elifoster** [comment]
Oh yes, we have already learned how horrible with Gradle I am.

**Comment by xbony2** [comment]
It's not that complicated :P the trick is to look at other people's and figure out how they work.

**Comment by Strikingwolf** [comment]
Just a question in general about this, do any editors/IDEs recognize the imports from mods?

**Comment by elifoster** [comment]
@Strikingwolf What do you mean?

**Comment by Strikingwolf** [comment]
So if I import from the mods directory (mods.modname.packagename.classname) then will an IDE recognize that as a valid import and know that the class can be accessed and what is in it

**Comment by elifoster** [comment]
IntelliJ should be able to do that if I'm understanding you correctly. So should Eclipse.

**Comment by Strikingwolf** [comment]
Hmmm, I guess I need to look into some of that ;)

I'm asking because of UpToDate, but it is good general knowledge to have

**Comment by xbony2** [comment]
Er, do you know java? :P

**Comment by Strikingwolf** [comment]
Yes I know Java...why do you ask? I know that IDEs can import things and recognize that, but I wasn't sure if they would do it correctly from the mods directory ;)

**Comment by elifoster** [comment]
Oh @xbony2 make sure to create a pull request so we can review it before you merge with master.

**Comment by xbony2** [comment]
Ok.

**Comment by elifoster** [comment]
This is solved as of @c7b0dd0
