### ISSUE TITLE
Floral Laurel doesn't display Mana on Botania items

### ISSUE THREAD

**Issue by Hosed** [Esteemed-Innovation/Flaxbeards-Steam-Power#273]
The Floral Laurel upgrade doesn't display Mana for Botania items.

From what I can tell the fault lies in SteamcraftEventHandler line 380-390 where it checks for the upgrade being present in the ExoSuit Chest (slot 3) rather then the Helmet (slot 4) where the upgrade is placed.  This causes the line BotaniaIntegration.displayThings is never be executed.

I believe this is a hold over from getCurrentArmor where slot 3 was the helm (Not a Minecraft Modder, just been doing some google searches to understand the code and the plethora of magic numbers in Minecraft).

**Comment by xbony2** [comment]
This will be fixed once the branches merge, which hopefully will be soon.
