### ISSUE TITLE
Refer to recipe sorter

### ISSUE THREAD

**Issue by Adaptivity** [Esteemed-Innovation/Flaxbeards-Steam-Power#279]
Getting this in the log: *Unknown recipe class! flaxbeard.steamcraft.handler.CanisterHandler Modder please refer to net.minecraftforge.oredict.RecipeSorter*.
This minor issue actually a very easy to fix. One or two lines change.

**Comment by xbony2** [comment]
Feel free to send a Pull Request if you know how to fix it :P

**Comment by Adaptivity** [comment]
I'm not 100% sure how to fix it. But here an example how to do that: https://github.com/SlimeKnights/TinkersConstruct/commit/455b92eb1384c8ed46e487342ed413c8f2827019

**Comment by xbony2** [comment]
Ours is a little bit different, but I think I can figure it out.

**Comment by elifoster** [comment]
@xbony2 Any news on your ability to figure it out?

**Comment by Adaptivity** [comment]
I can try to fix that.
