### ISSUE TITLE
Crash on shift right-click with info book

### ISSUE THREAD

**Issue by Nate954** [Esteemed-Innovation/Flaxbeards-Steam-Power#281]
If you hold shift and right click on anything while holding the Esteemed Innovation info book, the server will crash.

**Comment by xbony2** [comment]
I just know there was another issue on this but I can't freakin' find it >.>

**Comment by Nate954** [comment]
Haha no problem, just as long as the issue is known!

**Comment by elifoster** [comment]
Can you provide a crash log? I'm skeptical to keep your issue open as this was allegedly fixed in 0.28.2, and there's no log to prove you are using the latest version.

**Comment by Nate954** [comment]
Oh I'm so sorry! my mistake, I'm running TPPI2 and they are not running your most recent version. All is good!

**Comment by xbony2** [comment]
It's ok :P
