### ISSUE TITLE
Config option for poor zinc ore

### ISSUE THREAD

**Issue by Qohelethh** [Esteemed-Innovation/Flaxbeards-Steam-Power#283]
When zinc ore is disabled from spawning in the overworld, poor zinc ore still spawns for me. Can we have a config option for that?

**Comment by elifoster** [comment]
That already exists.

**Comment by Qohelethh** [comment]
Ah, okay. I want the poor zinc ore to exist, I'm just using a COFH to do the ore gen. Will setting "Railcraft Poor Ore"=true still allow me to generate poor zinc ore using COFH? Or does it disable the block entirely?

**Comment by elifoster** [comment]
It disables it entirely. I suppose we could have a "keep ore blocks without spawning" config option. Would that suit your needs?

**Comment by Qohelethh** [comment]
Yes! If it's not too much trouble. It might be kind of a fringe usage, but that's exactly what I want to do.

**Comment by elifoster** [comment]
Okay, started a new issue for it to keep this conversation separate. #284

**Comment by Qohelethh** [comment]
Thank you!
