### ISSUE TITLE
Pressure Pipe converter makes crash the game and corrupt the world

### ISSUE THREAD

**Issue by Craftosamus** [Esteemed-Innovation/Flaxbeards-Steam-Power#286]
Hi! I'm playing with my friend on Blast Off 1.3.4. We are on Flaxbeard's machines and we try to avoid pipe explosion. So i placed a pressure converter and then a buildcraft pipe with redstone engines and tanks. When i launch the boiler, i get this annoying crash that corrupt the world :
http://pastebin.com/XqNvmQrM
This is very annoying because i don't know how to fix it and I had find no other way to evacuate pressure automatically!
Can someone help me ?

**Comment by elifoster** [comment]
Could I have a picture of your setup?

**Comment by Craftosamus** [comment]
![flaxconfig](https://cloud.githubusercontent.com/assets/12880594/8150474/e7df0dc8-12eb-11e5-9309-0aea89074141.jpg)

**Comment by Craftosamus** [comment]
So? You prefer a screenshot? Cause i don't want to corrupt again my world

**Comment by elifoster** [comment]
No thats ok. Im just not sure why it's happening

**Comment by Craftosamus** [comment]
Maybe a conflict with other mods from blast off. Or a thing that is missing in this modpack

**Comment by elifoster** [comment]
I am going to delay this bug because I have absolutely no idea what is causing it

**Comment by Divineaspect** [comment]
Cannot reproduce, and I've been doing a LOT of this on my server.
