### ISSUE TITLE
Crash on initialization

### ISSUE THREAD

**Issue by BillboardEric** [Esteemed-Innovation/Flaxbeards-Steam-Power#292]
http://hastebin.com/wocoxagoni.1c

**Comment by ate0ate** [comment]
I believe I have the same issue...
http://pastebin.com/inkNpcUU

**Comment by elifoster** [comment]
That's weird, because the class that it looks like is causing the issue hasn't been touched in 10 months. I'll take a closer look at it later tonight probably.

**Comment by SJ1133** [comment]
Similar Crash: http://hastebin.com/iyocumabew.1c

**Comment by elifoster** [comment]
Right now I am *still* having issues testing FSP, this time because of some mod wanting NEI 1.0.4 even though 1.0.5 is being used (@xbony2). When Xbony can tell me how to fix this/fix this I will take another look. Though I may be away for a couple days or something.

**Comment by mindcloud69** [comment]
Same crash here.

**Comment by elifoster** [comment]
Use 0.28.7 until 0.28.9 is released
