### ISSUE TITLE
Tool Heads is not included in the new crossmod stuff

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#293]
The Tool Heads API is still in src rather than fsplibs or whatever. This should have been done in #274, but neither of us noticed.

Also see #149

**Comment by xbony2** [comment]
This was lazily fixed in [this commit](https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/commit/48164555adabb4250668d6f020f57ab05c0975f6).
