### ISSUE TITLE
Musket shots seem to get Blocked by tall grass.

### ISSUE THREAD

**Issue by PaperTriangle** [Esteemed-Innovation/Flaxbeards-Steam-Power#295]
As the title says. Firing the musket (or any weapon that fires the same projectile) seems to be unable to shoot through tall grass, or other similar blocks.

**Comment by elifoster** [comment]
I'm not sure how we would even solve this, but I also haven't looked at the code. I'll look at it tomorrow.

**Comment by elifoster** [comment]
Musket shots will now go through any block that is of the material air, coral, vine, water, fire, web, or plants.

**Comment by PaperTriangle** [comment]
This issue is still present in the latest update.

**Comment by elifoster** [comment]
Thats really weird as I extensively tested it after fixing it for like 20 minutes with a bunch of variations
