### ISSUE TITLE
Mekanism new world crash

### ISSUE THREAD

**Issue by Tsyklop** [Esteemed-Innovation/Flaxbeards-Steam-Power#308]
I found that this mode does not allow to create a new world and play in the old.
When creating or loading an old world throws to the main menu.
I looked in the log file and saw a error.
The log participates Mekanism without FSP everything is fine ...

Error: http://pastebin.com/qFJ3Fya3

And: https://github.com/aidancbrady/Mekanism/issues/2933

**Comment by elifoster** [comment]
Duplicate of #298
