### ISSUE TITLE
DEVS: Post here for GFX requests

### ISSUE THREAD

**Issue by Drullkus** [Esteemed-Innovation/Flaxbeards-Steam-Power#315]
Seriously, poke me or something when you need textures. This ticket might be a good idea to keep a log of all GFX requests for FSP.

EDIT: To poke anyone in the GFX team, tag @Esteemed-Innovation/aesthetics-team :)

**Comment by elifoster** [comment]
We should also just tag the aesthetics team in case one of you guys are away on leave or something

**Comment by Drullkus** [comment]
You mean on the labels?

**Comment by elifoster** [comment]
No I mean when one of the devs is posting here, @esteemed-innovation/aesthetics-team

**Comment by Drullkus** [comment]
Ah, that will work too :)

**Comment by elifoster** [comment]
Oh right this issue is a thing. I need Foggles. See #324

**Comment by elifoster** [comment]
Rain-Away texture is needed. I don't really have any clue what it should look like, so uh, use your artistic magic and provide some samples? It's a helmet upgrade.

**Comment by Drullkus** [comment]
I've both of my arms tied behind my back with [Shizzel](https://github.com/Drullkus/Shizzel) at the moment, but I can make the model for you after Shizzel's first release along with all requested textures..

**Comment by elifoster** [comment]
Alright. I'm worried about leaving the exo-cosmetics branch to get stale. I'm currently deciding on whether I should submit a PR so @xbony2 and/or @Strikingwolf can perform a code review and we can get it merged, despite the lack of a recipe for the Rain-Away. What do you think, since you're the one who knows at least a guess of how long the textures and models will take to get pushed to the resources repo?

**Comment by Drullkus** [comment]
I don't know how long Shizzel will take.

**Comment by elifoster** [comment]
I'll wait 1-2 weeks and check in again. And maybe @Blorph can handle it since you are busy...

**Comment by Flaxbeard** [comment]
I can try to whip something up this week

**Comment by xbony2** [comment]
Huh? Who are you?

/s

**Comment by Drullkus** [comment]
Whoa, a mysterious stranger to the rescue! 

/s

**Comment by elifoster** [comment]
I'm going to close this. Just watch your notifications and watch issues that involve new features.
