### ISSUE TITLE
Crash when Looking at the Ores Page of Esteemed Innovation

### ISSUE THREAD

**Issue by Arouka** [Esteemed-Innovation/Flaxbeards-Steam-Power#321]
http://pastebin.com/HCsBzPkk

Tried to remove More player models, the problem persisted

**Comment by elifoster** [comment]
Can you give us the crash report when you removed mpm?

**Comment by elifoster** [comment]
Wow, the bit of code causing the issue sucks... I think I know why this is happening.

**Comment by elifoster** [comment]
@xbony2 Crash bugs are always prio;high.

**Comment by elifoster** [comment]
I'm currently unable to reproduce this issue in my development environment.
