### ISSUE TITLE
Server crash: NoClassDefFound

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Esteemed-Innovation/Flaxbeards-Steam-Power#322]
http://hastebin.com/isekihabin.md

**Comment by Drullkus** [comment]
Sounds a @SideOnly(Side.Client) was forgotten somewhere.

**Comment by elifoster** [comment]
That's what I was thinking, I'm just not sure where. I'm pretty sure the ExosuitCache stuff should be server-side, but it looks like ModelBiped is only available client-side.

**Comment by elifoster** [comment]
I'm currently unable to reproduce this issue due to another crash caused by EnderIO. When I figure that out, I'll test again and hopefully move this issue over to the ready state.

**Comment by cauliflower69** [comment]
Getting the same error after updating your mod
