### ISSUE TITLE
Add support MineTweaker

### ISSUE THREAD

**Issue by Tsyklop** [Esteemed-Innovation/Flaxbeards-Steam-Power#323]
Please. Addd support MinetWeaker for FSP

**Comment by elifoster** [comment]
Isn't it supported by ModTweaker? That was discussed in #179.

**Comment by Drullkus** [comment]
It appears [support was dropped](http://minetweaker3.powerofbytes.com/wiki/ModTweaker).

**Comment by elifoster** [comment]
Hm. Bummer. @Drullkus do you know if it's actually good practice to natively support MineTweaker? Or should someone just go complain to the ModTweaker guys that we aren't supported anymore?

**Comment by Tsyklop** [comment]
@elifoster look here https://github.com/jaredlll08/ModTweaker2/issues/239

**Comment by elifoster** [comment]
I am awaiting a response from the developers of ModTweaker2 so that I can decide on whether we should support it natively, or just add the APIs so that they can handle it.

**Comment by elifoster** [comment]
Closing in favor of #327.
