### ISSUE TITLE
API needed functions for ModTweaker

### ISSUE THREAD

**Issue by xbony2** [Esteemed-Innovation/Flaxbeards-Steam-Power#327]
Some of these probably exist.
* Steam Heater
  * [x] Adding- can be covered by SteamcraftRegistry.addSteamingRecipe()
  * [x] Removing- can be covered by SteamcraftRegistry.removeSteamingRecipe()
* Rock Smasher
  * [x] Adding- can be covered by SmashablesRegistry.registerSmashable()
  * [x] Removing can be covered by SmashablesRegistry.removeSmashable()
* Crucible
  * [x] Adding a liquid- covered by SteamcraftRegistry.registerLiquid()
  * [x] Removing a liquid- covered by SteamcraftRegistry.removeLiquid()
  * [x] Adding a melting recipe- covered by SteamcraftRegistry.registerMeltRecipe(), registerMeltRecipeOreDict, and registerMeltRecipeTool
  * [x] Removing a melting recipe- covered by SteamcraftRegistry.removeMeltRecipe() (and removeLiquid())
  * [x] Adding a dunking recipe- covered by SteamcraftRegistry.registerOreDictDunkRecipe(), registerDunkRecipe()
  * [x] Removing a dunking recipe- covered by SteamcraftRegistry.removeDunkRecipe() and removeOreDictDunkRecipe()
* Carving Table
  * [x] Adding- SteamcraftRegistry.addCarvableMold()
  * [x] Removing- SteamcraftRegistry.removeMold()

**Comment by elifoster** [comment]
@xbony2 Is this in-progress? If so, please remove ready and add in progress.

**Comment by xbony2** [comment]
Why'd you add ready? ;p

**Comment by elifoster** [comment]
Because I wasn't sure if anyone was working on it at the time, and waffle.

**Comment by elifoster** [comment]
@xbony2 Any word on the progress for this?

**Comment by elifoster** [comment]
Can't you already register dunk recipes with `registerDunkThing` and `registerDunkThingOredict`, and register melt recipes with `registerSmeltThing` and `registerSmeltThingOredict`? You could remove them by modifying the dunkThings and smeltThings hasmaps, couldn't you?
