### ISSUE TITLE
Steam Hammer progress issue

### ISSUE THREAD

**Issue by ElykeSly** [Esteemed-Innovation/Flaxbeards-Steam-Power#33]
Version: 0.23.0
Bug Type: Performance
Environment: SSP
Gamemode: Survival
Description: A Steam Hammer with work (Binding, Renaming, etc.) will forcibly stop the progress when the user:
{A} Dies
{B} Disconnect+Connects

**Comment by elifoster** [comment]
I was an idiot 3 months ago. Reopening.
