### ISSUE TITLE
Crash when disabling copper ore without disabling zinc ore generation.

### ISSUE THREAD

**Issue by Rukachan** [Esteemed-Innovation/Flaxbeards-Steam-Power#330]
The crash happens after I create a new world.

Flaxbeard's Steam Power 1.7.10-0.28.12
Forge 10.13.4.1448

Here is the relevant part of the crashlog: http://pastebin.com/W5eNFfWv

**Comment by elifoster** [comment]
Can you provide your config file as well as the full crash log?

**Comment by Rukachan** [comment]
crashlog: http://pastebin.com/fQniCtnP
config: http://pastebin.com/Ksz9h8P6
The only thing that I changed from the original config is to turn B:"Enable Copper Ore. This does not enable world generation of the ore, but will disable it if false." to false. The crash still happens when I turn "Generate Overworld Copper" and/or "Generate Copper in the above extra dimensions" to false.

**Comment by elifoster** [comment]
[I think I know the cause of this crash](https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/SteamcraftBlocks.java#L78)

**Comment by elifoster** [comment]
I think I'm just going to remove the config options to disable them, because due to metadata the blocks are dependent on each other.

**Comment by Drullkus** [comment]
@elifoster Just remove them from worldgen in the cfg.

**Comment by elifoster** [comment]
That's what I did? I'm not sure I understand what you mean.

**Comment by Drullkus** [comment]
Ah ok.
