### ISSUE TITLE
Thorough API Documentation

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#340]
@Esteemed-Innovation/lead-developers I think we should start a project in which we use the GitHub Wiki as a place for documentation on using our API. As I stated in IRC:
> JavaDocs are good, yes, but you can't get fully detailed with intricate examples

**Comment by xbony2** [comment]
You could put it on the actual wiki. Github Wikis are eh.

**Comment by elifoster** [comment]
I thought about that, but we haven't really done any API documentation there as far as I'm aware. We'd need conventions for that and shit. I suppose this is now a discussion for the FTB Wiki.

**Comment by elifoster** [comment]
Pretty sure we came to the consensus to have a general modding guide for FSP on the actual wiki, and to just have good documentation in the code.
