### ISSUE TITLE
Remove calls to ReflectionHelper from high traffic code

### ISSUE THREAD

**Issue by LemADEC** [Esteemed-Innovation/Flaxbeards-Steam-Power#353]
ReflectionHelper is fairly slow to execute by design. It's intended to be used once, during server init or something alike.
As seen in https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/handler/SteamcraftEventHandler.java#L454
There's 2 to 4 calls to that library for every LivingUpdateEvent() on a villager.
Due to this, the mod is 6 times slower than other mods in processing this event.

Other occurrences might exist elsewhere in the code, notably here: https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/a84a1f34bd3ddf1a2d996e80102e2a355a54b219/src/main/java/flaxbeard/steamcraft/tile/TileEntityCustomFurnace.java#L290

**Comment by elifoster** [comment]
Yikes! We reference it 33 times! I'll look into all of these references.

**Comment by elifoster** [comment]
I'm able to remove a bunch of the ReflectionHelper references, except for that first one you listed. I'm not really sure how to access those villager fields without reflection.

**Comment by elifoster** [comment]
That tile entity code shouldn't ever be called because the custom furnace block (and crafting table) never get initialized... I'll change it anyway in case we actually make those blocks do things.

**Comment by elifoster** [comment]
Now that those are out of the way, we still use reflection when rendering crafting pages, and on villager updates.

I took a look in the Botania source, because our book code is similar, and they use reflection to render crafting recipes as well. On top of that, the only thread I could find about ShapedOreRecipe#width and #height included Lex rejecting making these fields public.

As for villagers, @Strikingwolf and @xbony2 do you guys have any ideas on how to improve that code?

**Comment by LemADEC** [comment]
You can make the field public dynamically, like I did for arrows in the Runic Dust mod (HellStorm Rune):

```
	private static Field fieldInGround = null;
	
	static {
		// open access to EntityArrow.inGround
		Class<?> classEntityArrow = EntityArrow.class;
		try {
			fieldInGround = classEntityArrow.getDeclaredField("inGround");
		} catch (Exception exception1) {
			try {
				fieldInGround = classEntityArrow.getDeclaredField("field_70254_i");
			} catch (Exception exception2) {
				exception2.printStackTrace();
				String map = "";
				for(Field field : classEntityArrow.getDeclaredFields()) {
					if (!map.isEmpty()) {
						map += ", ";
					}
					map += field.getName();
				}
				DustMod.logger.error("Unable to find inGround field in " + classEntityArrow + " class. Available fields are: " + map);
			}
		}
		if (fieldInGround != null) {
			fieldInGround.setAccessible(true);
		}
	}
...
	@Override
	public void onTick(EntityRune entityRune) {
...
					try {
						if (fieldInGround != null && fieldInGround.getBoolean(entityArrow)) {
							// do something...
						}
					} catch (Exception exception) {
						exception.printStackTrace();
						DustMod.logger.error("Disabling reflexion...");
						fieldInGround = null;
					}
...
	}
```

In your case, field_70961_j is timeUntilReset and field_82189_bL is lastBuyingPlayer

**Comment by elifoster** [comment]
Ah, thank you for that. I'm still very raw when it comes to reflection

**Comment by elifoster** [comment]
@LemADEC Does it matter which phase of initialization that occurs it? I'd imagine preInit, but I can't really find any information about it in regards to MCF itself.

**Comment by LemADEC** [comment]
I do it in the static constructor of the class, so it's done when the class is instantiated, typically during  init phase.
