### ISSUE TITLE
handleSteamcraftArmor is 3 times slower than other mods

### ISSUE THREAD

**Issue by LemADEC** [Esteemed-Innovation/Flaxbeards-Steam-Power#354]
After doing a 21 mn profiling on our server, we've noted that handleSteamcraftArmor is about 3 times slower to process than other mods, notably when calling removeGoodExoBoost(), removeBadExoBoost(), hasPower() and getExoArmor().
Following review of the current code here: https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/handler/SteamcraftEventHandler.java#L1223

I would suggest the following changes:
1- check if entity is human before everything else since there's more mobs than players on a server.

2- regarding removeGoodExoBoost() and removeBadExoBoost(), it seems only required for resynchronisation, I would suggest to do it only once per second or so, something like if (entity.ticksExisted % 20 == 0) { }. Or we could execute the whole event processing only every 5 ticks as a whole?

Similar issues seem present in handleFlippers().

**Comment by elifoster** [comment]
1. We already do that, however, not in the code in the latest version. That was added in 714359c so you'll see it in 0.29.0.
2. I'll look into those methods.

**Comment by LemADEC** [comment]
1- this is not fixed in the code you're referencing to
```
     @SubscribeEvent
     public void handleSteamcraftArmor(LivingEvent.LivingUpdateEvent event) {
         boolean hasPower = hasPower(event.entityLiving, 1);
         int armor = getExoArmor(event.entityLiving);
         EntityLivingBase entity = event.entityLiving;
          ItemStack armor2 = entity.getEquipmentInSlot(1);
          //Steamcraft.proxy.extendRange(entity,1.0F);
  
         if (!(entity instanceof EntityPlayer)) {
             return;
         }

```

should be

```
     @SubscribeEvent
     public void handleSteamcraftArmor(LivingEvent.LivingUpdateEvent event) {
         if (!(entity instanceof EntityPlayer)) {
             return;
         }

         boolean hasPower = hasPower(event.entityLiving, 1);
         int armor = getExoArmor(event.entityLiving);
         EntityLivingBase entity = event.entityLiving;
          ItemStack armor2 = entity.getEquipmentInSlot(1);
          //Steamcraft.proxy.extendRange(entity,1.0F);
 ```

**Comment by elifoster** [comment]
Oh, yeah.
