### ISSUE TITLE
Exosuit Steam FIller charging issue when Item Physics is installed

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#357]
See [this video](https://www.youtube.com/watch?v=4NW-1pHvNNE)

Reported on the MCF by unggod

**Comment by elifoster** [comment]
@CreativeMD Does this need to be fixed on my end or yours? I see a very similar issue at CreativeMD/ItemPhysic#15.

**Comment by CreativeMD** [comment]
I will contact the author of this mod, there is no way to fix it from my side.

**Comment by CreativeMD** [comment]
There is a rather easy way to fix it.
If you enable
```RenderItem.renderInFrame = true;```
before rendering and disable it again (after rendering)
it will remove all those rendering glitches.
