### ISSUE TITLE
Server crash when using the Esteemed Innovation journal

### ISSUE THREAD

**Issue by Azutte** [Esteemed-Innovation/Flaxbeards-Steam-Power#362]
Clicked a nether crucible with the tutorial book! Everything died.

**Comment by elifoster** [comment]
Can you provide a crash log?

**Comment by Tristaric** [comment]
Tell me how to get a crash log from a server and I'll happily give it to you.

**Comment by elifoster** [comment]
If it's your server, get it from the crash-reports folder (or whatever the equivalent is).

If it's someone else's server, ask them for the crash report,

**Comment by Tristaric** [comment]
It's my server, I'll grab it real quick

**Comment by Tristaric** [comment]
I think this is it..? http://pastebin.com/tHXQHaXu

**Comment by Azutte** [comment]
Unrelatedly (no crash, still weird) [this](http://imgur.com/a/ZP5He) is what it does SOMETIMES in single player

**Comment by elifoster** [comment]
@Tristaric That log is fine, though in the future, the crash report refers to `This crash report has been saved to: /home/minecraft/multicraft/servers/server17855/./crash-reports/crash-2016-02-08_01.52.51-server.txt` :smiley: 

@Azutte Ah yeah, that bug has been reported at #287.

**Comment by elifoster** [comment]
@Divineaspect can you confirm this, since it was allegedly fixed in 0.28.2?

**Comment by Divineaspect** [comment]
shift click but yes I can.

http://pastebin.com/e9Vg5hx3
