### ISSUE TITLE
Is the smasher's NEI handler supposed to be in the current version?

### ISSUE THREAD

**Issue by Azutte** [Esteemed-Innovation/Flaxbeards-Steam-Power#365]
Referencing [this](https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/5f70d3644a38b023f8d9a7366cef6d3d0a43943b/src/main/java/flaxbeard/steamcraft/integration/nei/handlers/RockSmasherHandler.java) and the fact that I cannot pull up a recipe for the smashed ore pieces, or... sand? It's hard to even say what I can and can not do with it, because there's no list provided by NEI or the instruction book in the mod.

**Comment by elifoster** [comment]
No, that is a 0.29 feature. Always look at the changelog, and remember that master is typically in-dev commits.
