### ISSUE TITLE
Need to jump to walk on slabs and stairs

### ISSUE THREAD

**Issue by LemADEC** [Esteemed-Innovation/Flaxbeards-Steam-Power#367]
As of f6ab0f4682e2b44f2dcafca5ef3374e5a86a5e1f, a player with no armor needs to jump on slabs or stairs, a player should only need to walk on those.
Issue is reproduced in single player with only FSP and Forge 7.99.39.1566.

Disabling the stepUp initialisation seems to fix it, here:
https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/entity/ExtendedPropertiesPlayer.java#L33

through it might be a more general issue related to saving the value here:
https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/handler/SteamcraftEventHandler.java#L1405

or restoring it in removeGoodExoBoost, here:
https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/handler/SteamcraftEventHandler.java#L1438

**Comment by elifoster** [comment]
This issue was supposedly solved last year at #153 but it was never confirmed how, so I would not doubt it still exists. I don't think that commit is relevant.

**Comment by LemADEC** [comment]
I was giving the commit as a version label where the issue is reproduced, sorry for the confusion.

Since we never know what other mod could do with that stepUp value, I would propose to only remember we've changed it and, when removing it, only restore to vanilla default value instead of a saved one. Ideally, we would check the current value before changing it.
