### ISSUE TITLE
Exosuits make players invincible.

### ISSUE THREAD

**Issue by GreenFoxx** [Esteemed-Innovation/Flaxbeards-Steam-Power#371]
So on my server the exosuit makes any wearer completely invincible! I have no idea why. I went into single player and tried it and the bug is not present there. The server uses kcauldron and we a custom modpack with mods listed here:       http://technicpack.net/modpack/industrial-conquest-modpack.810689

**Comment by elifoster** [comment]
This is possibly due to Cauldron. Are there any relevant logs?

**Comment by GreenFoxx** [comment]
Fixed it was kcauldron
