### ISSUE TITLE
Can't Create Then Join a New World

### ISSUE THREAD

**Issue by Infernalized** [Esteemed-Innovation/Flaxbeards-Steam-Power#381]
## Bug description
I cant create and join a world that I made with Flaxbeard's even after restarting the instance.
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:10.13.4.1492-1.7.10
* Flaxbeard's Steam Power version:1.7.10-0.28.12

## Crash report
```
CRASH REPORT HERE
```
This is my FML latest
http://pastebin.com/hLN1PcQU

And here is my crash report
http://pastebin.com/MVSSpERJ

**Comment by elifoster** [comment]
Can you provide your configuration file?

**Comment by Infernalized** [comment]
Looks like it is the same, http://pastebin.com/VzCJHtQP sorry about that didn't mean to get a duplicate issue up here.

**Comment by elifoster** [comment]
Try re-enabling the `Enable Copper Ore. This does not enable world generation of the ore, but will disable it if false.` option. Because of metadata, when that is turned off, it creates issues generating the other ore blocks.

**Comment by Infernalized** [comment]
Okay, Thanks! That fixed it.
