### ISSUE TITLE
Crash when using a steam tool in a fake player

### ISSUE THREAD

**Issue by Skyqula** [Esteemed-Innovation/Flaxbeards-Steam-Power#385]
## Bug description
Using a steam tool with either a Thaumic Tinkerers dynamism tablet or a Thermal Expansion autonomous activator causes a crash.

The dynamism tablet allows rejoining of the world, the autonomous activator however prevents world rejoining, making this a rather severe bug.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1558-1.7.10
* Flaxbeard's Steam Power version: 0.29.1

## Crash report
```
Thaumic Tinkerer: http://pastebin.com/q4hmmAXe
Thermal Expansion: http://pastebin.com/f79T6xhg
```

**Comment by xbony2** [comment]
We should make it so only real players can use steam tools.

**Comment by Divineaspect** [comment]
Until we have our own fake player.

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by xbony2** [comment]
"Fake players are cheaty and stupid" - Anonymous

**Comment by elifoster** [comment]
I think I found the issue. These fake players don't ever call onUpdate, so the IdentityHashMap I made never gets the stack, ticks, and speed added to it. Then we try to set the nbt as if it is not null. A simple containsKey check should fix this. Should.

**Comment by Divineaspect** [comment]
Confirmed
http://pastebin.com/twTV768E
