### ISSUE TITLE
Air Strike Conversion Kit wont work

### ISSUE THREAD

**Issue by renard162** [Esteemed-Innovation/Flaxbeards-Steam-Power#387]
## Bug description
Air Strike Conversion Kit wont work

Testing in a clean minecraft only with forge and FSP the Air Strike wont work anymore. I receive the firerate boost when I'm on ground but when I use rocket jump the boost is gone.

https://youtu.be/LeFp4gAyZKY

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Flaxbeard's Steam Power version: 0.29.1

**Comment by elifoster** [comment]
I've confirmed this bug.
