### ISSUE TITLE
crash when start

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Esteemed-Innovation/Flaxbeards-Steam-Power#388]
## Bug description
crash when start the game with the mod UniDict-1.3
http://minecraft.curseforge.com/projects/unidict
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:10.13.4.1614
* Flaxbeard's Steam Power version:0.29.1

## Crash report
https://gist.github.com/d5526c5618ba4757fe29f4eb3a4e9a36

**Comment by elifoster** [comment]
It looks like UniDict is stupidly removing OreDictionary entries. Nothing I can really do about that except convince you to tell the author to stop doing that. When they do that, they are bound to have issues like this.

They are much better ways to handle OreDictionary unification, like installing one of the many mods that allows you to manually and automatically switch all items in an OreDict entry to a specific version. I recommend you use that instead.

**Comment by SvEgiiVEteR** [comment]
@elifoster I do not know how to tell him he does not have threads issues

three modes in the error involved. I find him and show you crash

**Comment by elifoster** [comment]
I've told him that he shouldn't be deleting OreDict entries on his CF page.

**Comment by SvEgiiVEteR** [comment]
industrialcraft-2-2.2.821-experimental.jar =)))))))
https://gist.github.com/f94ae474c20a643ba8456a841b066bb4
without industrialcraft game starts)

thank you) I do not know much English ... I would not be able to explain to him

**Comment by SvEgiiVEteR** [comment]
That helped ))
 B:keepOneEntry=false
