### ISSUE TITLE
Items do not stack as they should

### ISSUE THREAD

**Issue by Warrino** [Esteemed-Innovation/Flaxbeards-Steam-Power#389]
## Bug description
After i added this mod to my modpack, some items do not stack as they should.
When i remove this mod the bug disappears.
Example:
After I place torch and i break it, it don't stack with other torch. (change metadata)
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Flaxbeard's Steam Power version: 0.29.1

List mod: 
- All infinity evolved 2.5.0
- Ars Magica 2
- Aroma
- Advanced Generator
- Mekanism
- NuclearCraft
- Trashslot

## Crash report
Game don't crash 
CRASH REPORT HERE
```

**Comment by Divineaspect** [comment]
Confirmed.

**Comment by kwpugh** [comment]
For folks that updated to 29.2, are you still seeing this problem?   Because I am still having the problem on my server.

**Comment by elifoster** [comment]
With items that already have the tags?

**Comment by kwpugh** [comment]
I don't have any tools (that I know of) to see what tags the items have.   Is there a way to do that?

**Comment by elifoster** [comment]
Use MineTweaker /mt hand.
