### ISSUE TITLE
Lumber Chain ineffective on MFR Rubber Trees

### ISSUE THREAD

**Issue by Divineaspect** [Esteemed-Innovation/Flaxbeards-Steam-Power#393]
## Bug description
Lumber Chain ineffective on MFR Rubber Trees
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:
* Flaxbeard's Steam Power version:0.29.2 dev build

## Crash report
```
No crash, just no special effect.
```

**Comment by elifoster** [comment]
Blame MFR. I'll submit a PR to MFR that would resolve this. They didn't register their logs to the log oredict.

**Comment by elifoster** [comment]
I've submitted the PR at skyboy/MineFactoryReloaded#552. If it gets rejected, I'll add another rule to the OreDictHelper to assign leavesMaterial and woodMaterial to the leaves and logs, I guess. I'd prefer it just get merged though, so we don't get bad side effects like some random woodBlock from another mod getting treated as a tree.

**Comment by elifoster** [comment]
Set the milestone in case that PR doesn't get merged into MFR.

**Comment by elifoster** [comment]
I'd rather not special case it, actually. If that PR doesn't get merged, just add the logs to the proper oredict entry using minetweaker.
