### ISSUE TITLE
Saw breaks when it runs out of steam

### ISSUE THREAD

**Issue by Divineaspect** [Esteemed-Innovation/Flaxbeards-Steam-Power#399]
## Description

The saw broke when I was chopping my way through a natura redwood.

## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:
* Flaxbeard's Steam Power version:0.29.2 dev

## Crash report
```
CRASH REPORT HERE
```

**Comment by elifoster** [comment]
Does it only happen when you have the Timber Chain installed? That was the only way I could reproduce it in my development environment.

**Comment by Divineaspect** [comment]
just got the same issue with a steam drill.

**Comment by elifoster** [comment]
With what upgrade(s)? I am going to go and change all setDamage or damageItem calls to addSteam calls, because they are superior.
