### ISSUE TITLE
Steam Drill, diamond void isn't using the last 800 su no matter how I rev it.

### ISSUE THREAD

**Issue by Divineaspect** [Esteemed-Innovation/Flaxbeards-Steam-Power#400]
## Description
Steam Drill, diamond void isn't using the last 800 su no matter how I rev it.
## Base information
* Minecraft version:
* Minecraft Forge version:
* Flaxbeard's Steam Power version:0.27.2dev

## Crash report
```
CRASH REPORT HERE
```

**Comment by elifoster** [comment]
it is probably just using the Exosuit's steam.
