### ISSUE TITLE
Exosuit Slots make little to no sense with upgrades

### ISSUE THREAD

**Issue by Divineaspect** [Esteemed-Innovation/Flaxbeards-Steam-Power#404]
## Base information
* Minecraft version:
* Minecraft Forge version:
* Flaxbeard's Steam Power version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by elifoster** [comment]
How so?

**Comment by Divineaspect** [comment]
For example: Rebreather and Tophat use the same slot, dispite one being atop the head, the other in front of the face.

**Comment by elifoster** [comment]
It's a trivial change, so if you could provide a list of what doesn't make sense and perhaps the slot that they should be in, that'd be good.

**Comment by Divineaspect** [comment]
actually that was the main one, but the foot upgrades don't feel consistent.
