### ISSUE TITLE
Unequipping empty exosuit does not remove slow condition.

### ISSUE THREAD

**Issue by SHWB** [Esteemed-Innovation/Flaxbeards-Steam-Power#413]
## Description

The title is self explanatory.
This is replicable following these steps:

1. Obtain a cool exosuit by crafting or cheating, and add a tank to it.
2. Wear it: you'll be slowed down because it's unpowered.
3. Take it off with no particular order: the slow effect persists. 

There are similar oddities when interacting with the armor stand from Bibliocraft. I'm not sure if I should open a different issue for this. However, this is what happens:

1. Put a powered exosuit on an armor stand (if not, the behaviour reported above will happen with the armor stands as well).
2. Wear your exosuit by shift+right clicking on each piece or opening the armor stand's inventory.
3. Now, here comes the tricky part: if you remove the exosuit pieces with the reverse process you'll be still slowed even after it's fully unequipped. **BUT** if you remove the chest piece last, everything works fine.

I'm also wondering if the two bugs are related. I haven't tried to replicate this on vanilla + FSP only.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Flaxbeard's Steam Power version: 0.29.1

**Comment by elifoster** [comment]
Yep, already fixed in the next version. Close by bc5c95d
