### ISSUE TITLE
Crash at Initialization

### ISSUE THREAD

**Issue by GreatOrator** [Esteemed-Innovation/Flaxbeards-Steam-Power#414]
## Description
Since 0.29.0, still happening at 0.29.2, on startup during initialization phase flaxbeard's crashes to desktop.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1566
* Flaxbeard's Steam Power version: 0.29.0 - 0.29.2

## Crash report
http://pastebin.com/dmxcktZN

**Comment by elifoster** [comment]
Can you provide your config?

**Comment by GreatOrator** [comment]
Why yes I can...I just push updates so the most recent config is on my repo:

https://github.com/GreatOrator/TolkienCraftII/blob/master/client/minecraft/config/FlaxbeardsSteamPower.cfg

**Comment by elifoster** [comment]
You seem to have a bunch of duplicated config options there, some which have different values from one another (see Revolver enhancement). That is probably what is causing this. Try regenerating the config from scratch and adding the tweaks you have to the fresh one. At some point a long time ago I cleaned up grammar in the config, which is probably where these duplicated options came from.

**Comment by GreatOrator** [comment]
Makes perfect sense...will try that when I get home tonight and let you know if it worked.  I have seen duplication in other configs before but had not thought to check that for this.

**Comment by GreatOrator** [comment]
Yup, the config was the problem, thanks for pointing that out! :100:
