### ISSUE TITLE
crash when trying to modify Traveller's gear

### ISSUE THREAD

**Issue by b0bst3r** [Esteemed-Innovation/Flaxbeards-Steam-Power#439]
## Description
I am trying to put moss on my traveller's boots. When I put the boots in a crafting station,there is an instant crash. When I try and use a tool station, it allows me to put in the boots, but when I try to modify them, it crashes. Doesn't happen when I try to modify a TC tool, but it does happen when I try to modify the goggles or other traveller's gear.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: forge-1.7.10-10.13.4.1566
* Flaxbeard's Steam Power version: FSP-1.7.10-0.29.2

## Crash report
http://pastebin.com/wg6GGznW

https://github.com/BevoTechPack/BevoTechPack/issues/984

**Comment by elifoster** [comment]
@Lance5057 Do you know anything 'bout this? This issue is moderately confusing to me :P

**Comment by mallrat208** [comment]
The code for the Steam modifier makes the assumption that the item placed in the table will bee a Tinkers Tool and casts the item as such. The problem being that Tinkers armor is an instance of ArmorCore, not ToolCore. The only thing the two classes have in common is what they inherent from Item.

```
    @Override
    protected boolean canModify(ItemStack tool, ItemStack[] input) {
        NBTTagCompound tags = tool.getTagCompound().getCompoundTag("InfiTool");

        if (tags.getInteger("Modifiers") > 0 && !tags.getBoolean(key)) {
            return false;
        }
        
        if (Arrays.asList(((ToolCore) tool.getItem()).getTraits()).contains("ammo")) {
            return false;
        }
        
        return true;
    }
```

**Comment by Lance5057** [comment]
Ah, I did not account for travellers gear. I'll fix it when I get home.

**Comment by elifoster** [comment]
@Lance5057 Any word on this?

**Comment by Lance5057** [comment]
This has been fixed.

**Comment by elifoster** [comment]
You can close issues ya know :P
