### ISSUE TITLE
Third person journal entries

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#456]
## Description

When you are in third person view, the book reads in third person as well. However, there are a few issues with this.
- First, it does not handle context very well. It blindly replaces "have" with "has", so we get weird things like "they has exosuits".
- Second, it only handles English. We should be striving to make EI as accessible as possible. We need to handle third person stuff through localization rather than hard coding english words into the book. Perhaps there could be 2 localizations for every entry, and by omitting one whose key ends in "third" it would just go straight to the first person entry, to prevent errors. This would be kind of tedious, but I don't really see how it would work otherwise because different languages handle contexts and POV differently (for example, "they have" is translated to Spanish depending on the context and what "they" means; singular they: "Tiene", plural they: "Tienen"). @xbony2 you know stuff about localization

**Comment by xbony2** [comment]
```
When you are in third person view, the book reads in third person as well.
```

wat

**Comment by elifoster** [comment]
In first person view, the book uses first person pov, eg "I made steam shit". In third person view, the book uses third person pov, eg "They made steam shit".

**Comment by xbony2** [comment]
According to Flaxbeard this is an easter egg and doesn't really need any attention.

**Comment by elifoster** [comment]
All bugs need attention.
