### ISSUE TITLE
Always taking fall damage on server with jetpack

### ISSUE THREAD

**Issue by godemperoroftheworld** [Esteemed-Innovation/Flaxbeards-Steam-Power#457]
## Description

On a client, if i fall with a jetpack, and use the jetpack to slow my fall at the end, i dont take damage. On the server, no matter how slowly I land, i take full fall damage.
## Base information
- Minecraft version: 1.7.10
- Minecraft Forge version: 10.13.4.1558 and 10.13.4.1614
- Flaxbeard's Steam Power version: 0.29.3
## Crash report

```
CRASH REPORT HERE
```

Not applicable

**Comment by godemperoroftheworld** [comment]
A clarification. This initially occured in a modpack with 138 mods.
I tested with FSP isolated (completely) and the issue still occured
I tested using a vanilla forge server instead of cauldron and the issue still occured
I tested with mod version 0.29.2 as well, the issue still occured there.

**Comment by godemperoroftheworld** [comment]
https://www.youtube.com/watch?v=_k8mUr5i9Qc&feature=youtu.be
That would be a recording of the glitch.

Also, would this be the code that handles fall damage for jetpacks? (located in main/java/flaxbeard/steamcraft/packet):
http://pastebin.com/q0THizu5

**Comment by CasinoR** [comment]
This also happen when flying with vaccum and fans.

**Comment by elifoster** [comment]
@CasinoR Can you open another ticket for the vacuum and fan issue?
