### ISSUE TITLE
Invalid shaped ore recipe

### ISSUE THREAD

**Issue by bookerthegeek** [Esteemed-Innovation/Flaxbeards-Steam-Power#458]
## Description

When disabling the smasher, receive a CTD due to an "Invalid shaped ore recipe". This is due to the "Internal Processing Unit" requiring the smasher to craft. Suggest either dynamically setting the recipe for that to use a piston if the smasher is disabled, or also disabling it in addition to the smasher.
## Base information
- Minecraft version: 1.7.10
- Minecraft Forge version: 10.13.4.1614
- Flaxbeard's Steam Power version: 0.29.3
## Crash report

[Crash Report](https://gist.github.com/bookerthegeek/fb3cbe7210d99a87a7b36361c5589ec6)

```
java.lang.RuntimeException: Invalid shaped ore recipe: sco, s, null, c, net.minecraft.block.BlockChest@479111ba, o, net.minecraft.block.BlockObsidian@7cac93fe, 1xitem.steamcraft:internalProcessor@0
    at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:116)
    at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:30)
    at flaxbeard.steamcraft.SteamcraftRecipes.registerSteamToolUpgrades(SteamcraftRecipes.java:741)
    at flaxbeard.steamcraft.Steamcraft.postInit(Steamcraft.java:232)
```

**Comment by elifoster** [comment]
This has been fixed in 1.10 at one point. I fixed it a while ago but forgot to close this.
