### ISSUE TITLE
Ingredient: Kit bag

### ISSUE THREAD

**Issue by Divineaspect** [Esteemed-Innovation/Flaxbeards-Steam-Power#467]
it's a piece of wool, hide, or leather and a string.
If placed in your hotbar and used and it's empty it picks up all the other items in your hotbar.
If used it empties itself into your inventory, hotbar first, and ordered.

creative and mob drop version has random stuff in it, like chunks of ore, ammo, or other things we want to hand out.

**Comment by elifoster** [comment]
For creative/mob drop versions it might be useful to use loot tables, which would be configurable.
