### ISSUE TITLE
Digging a block with the big drill breaks nearby bedrock

### ISSUE THREAD

**Issue by Geird** [Esteemed-Innovation/Flaxbeards-Steam-Power#474]
## Description
When the steam drill is equipped with the big drill attachment and you mine stones while the drill is active, it will also break and drop adjacent bedrock blocks. 
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614-1.7.10
* Esteemed Innovation version: 0.29.2

[Mod list and relevant images](http://imgur.com/a/65H58)

**Comment by elifoster** [comment]
Huh. I fixed this already at #397, but I can't find it in the changelog. It should be fixed by 0.29.2, so it's strange that it's still occurring. Can you try updating to 0.29.3?

**Comment by Geird** [comment]
Updated. MultiMC still displays it as .029.2 despite literally dragging 0.29.3 in. Drill breaks all the bedrock now instead of missing a corner. Still occasionally digs really slow even when spun to full speed, when otherwise it would cut through the rock like butter.

**Comment by elifoster** [comment]
>missing a corner.

Yeah I'm not really sure why that happens sometimes. Been trying to figure it out for months now.

>Still occasionally digs really slow even when spun to full speed, when otherwise it would cut through the rock like butter.

The way we handled the breakspeed in 1.7 was pretty crappy and I didn't really figure out why it was so inconsistent until last week (1.10.2). It's consistent in the next version.

As for the actual bedrock, I'm not really sure. I will test this in the current dev release when I get a chance and close/fix accordingly.
