### ISSUE TITLE
Regenerating ore toggleability

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#479]
## Description
Regenerating ores should be toggleable in the configuration file, with the default state being false. This'll disable the entire generation of regenerating ore nodes (including the worked out areas).

I feel like most people, myself included, won't particularly want to use the regenerating ores in their playthrough. It's kind of a specific style of play, I feel, and most people just want to be able to go mining and find some ore (in our case, in specific biomes).

**Comment by Divineaspect** [comment]
we could replace it with gnomes?

**Comment by elifoster** [comment]
Eh I like that idea better as its own mod. I think it would be enjoyed on its own without EI necessarily.
