### ISSUE TITLE
ModTweaker integration

### ISSUE THREAD

**Issue by ghost** [Esteemed-Innovation/Flaxbeards-Steam-Power#507]
Hi, I want to talk about integration with modtweaker. I believe that mod came out pretty well and I don't know any other mod, with such interesting steam and steampunk component. However, whatever mod you full use when creating modpacks, should be a good integration with modtweaker. Do you have plans to fix the integration with modtweaker?

**Comment by ghost** [comment]
![default](https://cloud.githubusercontent.com/assets/23289124/25579452/b46b1d80-2e80-11e7-8a82-9b2b3e60204c.PNG)

**Comment by elifoster** [comment]
We added MineTweaker integration in the latest feature version for 1.7.

**Comment by ghost** [comment]
Thank you for the quick response

**Comment by bookerthegeek** [comment]
@elifoster do you have documentaion for it or would you like me to update the wiki for you on it?

**Comment by xbony2** [comment]
There is, [here](https://ftb.gamepedia.com/Using_MineTweaker_and_Flaxbeard%27s_Steam_Power).

**Comment by bookerthegeek** [comment]
Thank you much.
