### ISSUE TITLE
FSP 0.25 quircks

### ISSUE THREAD

**Issue by OutcastZeroOne** [Esteemed-Innovation/Flaxbeards-Steam-Power#51]
nothing major to report, Just the Pressure Converter not showing up in the creative mode invintory. you have to craft it.

Also the steam whistle is very quiet. If I am 1-2 blocks away its loud. But if I go more then 5-6 blocks away its very quiet. Kind of defeats the purpuse of a warning system when you cant hear it. :/

The fan also will not show up in an item frame. Im guessing cause its a half block?

**Comment by elifoster** [comment]
Note that the fun bug is at #163
