### ISSUE TITLE
Compiling Error 1.12.2

### ISSUE THREAD

**Issue by Gandalf360one** [Esteemed-Innovation/Flaxbeards-Steam-Power#526]
I try to compile this mod to test it and use it in my Modpack, but I get that error:

misc.StringUtilityTest > testDecapitalize FAILED
    org.junit.ComparisonFailure at StringUtilityTest.java:23

misc.StringUtilityTest > testCapitalize FAILED
    org.junit.ComparisonFailure at StringUtilityTest.java:14

**Comment by elifoster** [comment]
My guess is that there is a Locale issue. Try commenting out line 154, `testCompile sourceSets.api.getOutput()` in `build.gradle`.
