### ISSUE TITLE
Issue with Schematica and BloodMagic

### ISSUE THREAD

**Issue by tahg** [Esteemed-Innovation/Flaxbeards-Steam-Power#98]
https://dl.dropboxusercontent.com/u/11334557/crash-2014-09-05_00.00.49-client.txt

Crashes with this whenever I try to enable Schematica's printer

**Comment by elifoster** [comment]
Why is a crash bug labeled with low priority?

**Comment by Divineaspect** [comment]
Doesn't seem to be an issue with modern Schematica, FSP, and blood magic.
